### ISSUE TITLE
Cloudflare blocking requests

### ISSUE THREAD

**Issue by prakharraj1302** [fspv/python-leetcode#19]

**Comment by fspv** [comment]
Well, I guess that's it then. I don't think I want to build solving captcha into this project.

The best you can do is to use some proxy via `configuration.proxy = "someproxyurl.com"`. But I guess this wouldn't work anyway, because Cloudflare will ban by the user agent anyway. There might be a way to hack it, but I'm definitely not going to retrofit this into this project.
